name: Deploy Terraform to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ./src
        run: terraform init

      - name: Terraform Plan
        working-directory: ./src
        run: |
          terraform plan \
            -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var "subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" \
            -var "tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./src
        run: terraform apply -auto-approve tfplan
