name: Deploy Terraform to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Ensure fmt & lockfile are up to date
        working-directory: ./src
        run: |
          terraform fmt -recursive
          terraform init -lockfile=./.terraform.lock.hcl
      - name: Commit fmt & lockfile changes
        if: ${{ steps.fmt.outputs.changed == 'true' || steps.init.outputs.lock_changed == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: terraform fmt and lockfile update"
          git push origin HEAD:main

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ./src
        run: terraform init

      - name: Terraform Plan
        working-directory: ./src
        run: |
          terraform plan \
            -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var "subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" \
            -var "tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./src
        run: terraform apply -auto-approve tfplan
